In [2]:
import torch
print(torch.__version__)

2.9.0+cpu


In [3]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([2.0, 4.0, 6.0])
vector

tensor([2., 4., 6.])

In [6]:
vector.ndim

1

In [7]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 3])

In [10]:
TENSOR = torch.Tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]],
                        [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]]])
TENSOR

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [11]:
TENSOR.ndim


3

In [12]:
TENSOR.shape

torch.Size([2, 4, 3])

In [13]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5506, 0.6622, 0.2012, 0.8391],
        [0.1222, 0.6580, 0.4094, 0.0952],
        [0.8092, 0.5552, 0.8389, 0.5920]])

In [14]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [15]:
tensor * 10

tensor([10, 20, 30])

In [16]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [17]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [19]:
x_reshaped.squeeze()
x_reshaped.squeeze().shape

torch.Size([9])

In [20]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [21]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [22]:
print(x_stacked.squeeze())
x_stacked.squeeze().shape


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])


torch.Size([4, 9])

In [23]:
print(z.squeeze())
z.squeeze().shape

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


torch.Size([9])

In [24]:
z_squeezed = z.squeeze()
z_squeezed, z_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [25]:
z_unsqueezed = z_squeezed.unsqueeze(dim=0)
z_unsqueezed, z_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [26]:
rdn = torch.rand(size=(224, 224, 3))
rdn.shape

torch.Size([224, 224, 3])

In [27]:
rdn_permuted = rdn.permute(2, 0, 1)
rdn_permuted.shape

torch.Size([3, 224, 224])

In [28]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
y = x.reshape(1, 3, 3)

In [30]:
y, y.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [31]:
y[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [32]:
y[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [33]:
y[0, 1, 2]

tensor(6.)

In [34]:
y[:, :, 1]

tensor([[2., 5., 8.]])

In [35]:
import numpy as np

In [36]:
array = np.arange(1., 10.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [37]:
tensor = torch.ones(7)
numpy_array = tensor.numpy()
tensor, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [38]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A, random_tensor_B)
random_tensor_A == random_tensor_B

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [39]:
RANDOM_SEED = 17
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A, random_tensor_B)
random_tensor_A == random_tensor_B

tensor([[0.4342, 0.5351, 0.8302, 0.1239],
        [0.0293, 0.5494, 0.3825, 0.5463],
        [0.4683, 0.0172, 0.0214, 0.3664]]) tensor([[0.4342, 0.5351, 0.8302, 0.1239],
        [0.0293, 0.5494, 0.3825, 0.5463],
        [0.4683, 0.0172, 0.0214, 0.3664]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [40]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.dtype, tensor.device

(tensor([1, 2, 3]), torch.int64, device(type='cpu'))

In [41]:
random_tensor_A

tensor([[0.4342, 0.5351, 0.8302, 0.1239],
        [0.0293, 0.5494, 0.3825, 0.5463],
        [0.4683, 0.0172, 0.0214, 0.3664]])

In [42]:
random_tensor_A.squeeze()

tensor([[0.4342, 0.5351, 0.8302, 0.1239],
        [0.0293, 0.5494, 0.3825, 0.5463],
        [0.4683, 0.0172, 0.0214, 0.3664]])

In [43]:
random_tensor_A.unsqueeze(dim=0)

tensor([[[0.4342, 0.5351, 0.8302, 0.1239],
         [0.0293, 0.5494, 0.3825, 0.5463],
         [0.4683, 0.0172, 0.0214, 0.3664]]])

In [45]:
random_tensor_A.unsqueeze(dim=1)

tensor([[[0.4342, 0.5351, 0.8302, 0.1239]],

        [[0.0293, 0.5494, 0.3825, 0.5463]],

        [[0.4683, 0.0172, 0.0214, 0.3664]]])